
import { PersonalizedWorkout, PersonalizedRecipe } from '@/types/aiTypes';

// UI Generator Service (Layer 2)
// Purpose: Transform Raw AI JSON -> Polished UI Props
// This decouples the "Brain" (Agentic Engine) from the "Face" (React Components)

export class UIGenerator {

    /**
     * transforms a raw workout plan into a rich visual card structure
     * @param rawPlan The raw JSON from the Agentic Engine
     */
    static generateWorkoutCard(rawPlan: any): PersonalizedWorkout {
        // 1. Sanitize Data
        const title = rawPlan.title || "AI Optimized Session";
        const difficulty = rawPlan.difficulty || "Intermediate";
        const duration = rawPlan.duration || "45 min";
        const calories = rawPlan.calories || 300;

        // 2. Enrich with UI Metadata (Icons, Colors, Badges)
        // In a real app, we might map 'difficulty' to specific colors here
        // e.g. 'Advanced' -> 'red', 'Beginner' -> 'green'

        // 3. Structure Exercises
        const exercises = Array.isArray(rawPlan.exercises) ? rawPlan.exercises.map((ex: any, idx: number) => ({
            id: `ex-${Date.now()}-${idx}`,
            name: ex.name || "Unknown Exercise",
            sets: ex.sets || "3",
            reps: ex.reps || "10",
            duration: ex.duration,
            description: ex.description || "Focus on form.",
            videoUrl: ex.videoUrl, // Agent might suggest a URL, or we lookup in DB
            targetMuscles: ex.targetMuscles || []
        })) : [];

        // 4. Construct Final UI Object
        return {
            id: rawPlan.id || `gen-workout-${Date.now()}`,
            title,
            description: rawPlan.description || "Generated by FitFuel Agentic Engine",
            difficulty,
            duration,
            calories,
            exercises,
            equipment: rawPlan.equipment || ["Bodyweight"],
            benefits: rawPlan.benefits || ["Full Body Activation"],
            category: rawPlan.category || "General",
            trainerNote: rawPlan.agentic_insight // The 'Liaison Agent' insight
        };
    }

    /**
     * transforms a raw recipe into a rich standard card
     */
    static generateRecipeCard(rawRecipe: any): PersonalizedRecipe {
        return {
            id: rawRecipe.id || `gen-recipe-${Date.now()}`,
            title: rawRecipe.title || "Chef's Selection",
            description: rawRecipe.description || "Nutrient dense meal.",
            prepTime: rawRecipe.prepTime || "15 mins",
            calories: rawRecipe.calories || 500,
            category: rawRecipe.category || "lunch",
            dietaryType: rawRecipe.dietaryType || "non-vegetarian",
            ingredients: rawRecipe.ingredients || [],
            steps: rawRecipe.steps || [],
            nutritionFacts: rawRecipe.nutritionFacts || { protein: 0, carbs: 0, fat: 0, fiber: 0 },
            tags: rawRecipe.tags || ["AI Chef"],
            chefNote: rawRecipe.agentic_insight // The 'Liaison Agent' insight
        };
    }
}
