-- 1. Profiles Table
CREATE TABLE public.profiles (
  id UUID REFERENCES auth.users(id) ON DELETE CASCADE PRIMARY KEY,
  full_name TEXT,
  email TEXT,
  username TEXT,
  dob TEXT,
  gender TEXT,
  weight_kg NUMERIC,
  height_cm NUMERIC,
  location TEXT,
  fitness_goal TEXT,
  fitness_level TEXT,
  diet_preference TEXT,
  has_completed_onboarding BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can only access own profile" ON public.profiles FOR ALL USING (auth.uid() = id);

-- Trigger to create profile on signup
CREATE OR REPLACE FUNCTION public.handle_new_user() 
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.profiles (id, email, full_name, created_at)
  VALUES (
    new.id, 
    new.email, 
    COALESCE(new.raw_user_meta_data->>'full_name', new.raw_user_meta_data->>'name', 'User'), 
    NOW()
  );
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();

-- 2. Anonymous Sessions
CREATE TABLE public.anonymous_sessions (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  session_token TEXT UNIQUE,
  device_id TEXT,
  user_agent TEXT,
  ip_address TEXT,
  expires_at TIMESTAMP WITH TIME ZONE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

ALTER TABLE public.anonymous_sessions ENABLE ROW LEVEL SECURITY;
-- Since they are anonymous, anyone can access by session token? Actually, typical apps don't strictly protect this table or use a token-based access.
-- Let's allow insert, and select/update if they know the token.
CREATE POLICY "Anon sessions select" ON public.anonymous_sessions FOR SELECT USING (true);
CREATE POLICY "Anon sessions insert" ON public.anonymous_sessions FOR INSERT WITH CHECK (true);
CREATE POLICY "Anon sessions update" ON public.anonymous_sessions FOR UPDATE USING (true);

-- 3. Workout Logs
CREATE TABLE public.workout_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  workout_id TEXT,
  workout_title TEXT,
  duration NUMERIC,
  calories_burned NUMERIC,
  exercises JSONB,
  notes TEXT,
  rating NUMERIC,
  date TIMESTAMP WITH TIME ZONE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

ALTER TABLE public.workout_logs ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can only access own workout_logs" ON public.workout_logs FOR ALL USING (auth.uid() = user_id);

-- 4. Workout Plans
CREATE TABLE public.workout_plans (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  title TEXT,
  description TEXT,
  workout_ids JSONB,
  exercises JSONB,
  difficulty TEXT,
  duration TEXT,
  benefits JSONB,
  schedule JSONB,
  is_active BOOLEAN,
  is_favorite BOOLEAN,
  source TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

ALTER TABLE public.workout_plans ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can only access own workout_plans" ON public.workout_plans FOR ALL USING (auth.uid() = user_id);

-- 5. User Favorites
CREATE TABLE public.user_favorites (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  item_id TEXT,
  item_type TEXT,
  item_title TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

ALTER TABLE public.user_favorites ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can only access own user_favorites" ON public.user_favorites FOR ALL USING (auth.uid() = user_id);

-- 6. User Progress
CREATE TABLE public.user_progress (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  date TIMESTAMP WITH TIME ZONE,
  weight NUMERIC,
  body_fat NUMERIC,
  muscle_mass NUMERIC,
  measurements JSONB,
  fitness_metrics JSONB,
  goals JSONB,
  notes TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

ALTER TABLE public.user_progress ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can only access own user_progress" ON public.user_progress FOR ALL USING (auth.uid() = user_id);

-- 7. Nutrition Logs
CREATE TABLE public.nutrition_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  food_name TEXT,
  calories NUMERIC,
  macros JSONB,
  image TEXT,
  meal_type TEXT,
  date TIMESTAMP WITH TIME ZONE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

ALTER TABLE public.nutrition_logs ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can only access own nutrition_logs" ON public.nutrition_logs FOR ALL USING (auth.uid() = user_id);

-- 8. AI Recipes
CREATE TABLE public.ai_recipes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  recipe_data JSONB,
  source TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

ALTER TABLE public.ai_recipes ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can only access own ai_recipes" ON public.ai_recipes FOR ALL USING (auth.uid() = user_id);

-- 9. Storage Setup
-- Creating a bucket for user uploads (Set to non-public for production security)
INSERT INTO storage.buckets (id, name, public) VALUES ('user_uploads', 'user_uploads', false)
ON CONFLICT (id) DO NOTHING;

-- Storage policies
CREATE POLICY "Users can view own objects" ON storage.objects FOR SELECT USING (bucket_id = 'user_uploads' AND auth.uid() = owner);
CREATE POLICY "Users can insert to user_uploads" ON storage.objects FOR INSERT WITH CHECK (bucket_id = 'user_uploads' AND auth.uid() = owner);
CREATE POLICY "Users can update own objects" ON storage.objects FOR UPDATE USING (bucket_id = 'user_uploads' AND auth.uid() = owner);
CREATE POLICY "Users can delete own objects" ON storage.objects FOR DELETE USING (bucket_id = 'user_uploads' AND auth.uid() = owner);

-- 10. Automated Maintenance
-- Enable pg_cron for background cleanup (Requires 'pg_cron' extension enabled in Supabase Dashboard)
-- Note: On hosted Supabase, you might need to enable this in the UI under Extensions first.
CREATE EXTENSION IF NOT EXISTS pg_cron;

-- Schedule cleanup of anonymous sessions older than 24 hours (runs daily at 3:00 AM)
SELECT cron.schedule(
  'cleanup-anonymous-sessions',
  '0 3 * * *',
  $$ DELETE FROM public.anonymous_sessions WHERE created_at < NOW() - INTERVAL '24 hours' $$
);
